"""add fields description, term, organization_info into TransactionOut

Revision ID: 1cc52e8509de
Revises: 23d46fdfcae9
Create Date: 2023-05-31 05:20:43.204385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc52e8509de'
down_revision = '23d46fdfcae9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_out', sa.Column('description', sa.String(), nullable=False))
    op.add_column('transaction_out', sa.Column('organization_info', sa.String(), nullable=False))
    op.add_column('transaction_out', sa.Column('term', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_out', 'term')
    op.drop_column('transaction_out', 'organization_info')
    op.drop_column('transaction_out', 'description')
    # ### end Alembic commands ###
