"""add region field to TransactionReport

Revision ID: 578453b9c5cb
Revises: 8a74d60da42f
Create Date: 2023-06-02 13:10:34.681911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578453b9c5cb'
down_revision = '8a74d60da42f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_report', sa.Column('region', sa.Enum('KRASNODAR', 'STAVROPOL', 'CRIMEA', 'ALTAI', 'PETESBURG', name='trregionenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_report', 'region')
    # ### end Alembic commands ###
