"""add spent field, transactions_in relationship

Revision ID: 5f8beae088a2
Revises: ac1b218a1ce8
Create Date: 2023-06-20 14:39:07.071870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8beae088a2'
down_revision = 'ac1b218a1ce8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transation_in', sa.Column('spent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transation_in', 'spent')
    # ### end Alembic commands ###
