"""add block_id, user_hash fields

Revision ID: 6abd40b6f903
Revises: a566a6ec502d
Create Date: 2023-05-03 13:34:38.421679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abd40b6f903'
down_revision = 'a566a6ec502d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('block_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('user_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'user_hash')
    op.drop_column('transactions', 'block_id')
    # ### end Alembic commands ###
