"""add cascade

Revision ID: 6ca7019bd4c1
Revises: 10875dbe3c12
Create Date: 2023-06-20 23:46:22.605953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca7019bd4c1'
down_revision = '10875dbe3c12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
