"""add тÑnew lds to TransactionReport

Revision ID: 8a74d60da42f
Revises: 1cc52e8509de
Create Date: 2023-06-01 12:33:01.049140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a74d60da42f'
down_revision = '1cc52e8509de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_out', sa.Column('executor_info', sa.String(), nullable=False))
    op.drop_column('transaction_out', 'organization_info')
    op.add_column('transaction_report', sa.Column('executor_info', sa.String(), nullable=False))
    op.add_column('transaction_report', sa.Column('tr_out_hash', sa.String(), nullable=False))
    op.drop_column('transaction_report', 'price')
    op.drop_column('transaction_report', 'customer')
    op.drop_column('transaction_report', 'executor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_report', sa.Column('executor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transaction_report', sa.Column('customer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transaction_report', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('transaction_report', 'tr_out_hash')
    op.drop_column('transaction_report', 'executor_info')
    op.add_column('transaction_out', sa.Column('organization_info', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('transaction_out', 'executor_info')
    # ### end Alembic commands ###
