"""create transaction tables

Revision ID: a566a6ec502d
Revises: 
Create Date: 2023-04-24 00:58:39.003421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a566a6ec502d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', 'REPORT', name='trtype'), nullable=False),
    sa.Column('tr_hash', sa.String(), nullable=True),
    sa.Column('tr_sign', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('transaction_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tr_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.Enum('KRASNODAR', 'STAVROPOL', 'CRIMEA', 'ALTAI', 'PETESBURG', name='trregionenum'), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILURE', name='trpaymentstatus'), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tr_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_out_id'), 'transaction_out', ['id'], unique=False)
    op.create_table('transaction_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tr_id', sa.Integer(), nullable=True),
    sa.Column('executor', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tr_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_report_id'), 'transaction_report', ['id'], unique=False)
    op.create_table('transation_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tr_id', sa.Integer(), nullable=True),
    sa.Column('operator_hash', sa.String(), nullable=False),
    sa.Column('tourist_hash', sa.String(), nullable=False),
    sa.Column('num_tourist', sa.Integer(), nullable=False),
    sa.Column('region', sa.Enum('KRASNODAR', 'STAVROPOL', 'CRIMEA', 'ALTAI', 'PETESBURG', name='trregionenum'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILURE', name='trpaymentstatus'), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tr_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transation_in_id'), 'transation_in', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transation_in_id'), table_name='transation_in')
    op.drop_table('transation_in')
    op.drop_index(op.f('ix_transaction_report_id'), table_name='transaction_report')
    op.drop_table('transaction_report')
    op.drop_index(op.f('ix_transaction_out_id'), table_name='transaction_out')
    op.drop_table('transaction_out')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
