"""add not null  region field to TransactionReport

Revision ID: ac1b218a1ce8
Revises: 578453b9c5cb
Create Date: 2023-06-02 13:13:58.792136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac1b218a1ce8'
down_revision = '578453b9c5cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_report', 'region',
               existing_type=postgresql.ENUM('KRASNODAR', 'STAVROPOL', 'CRIMEA', 'ALTAI', 'PETESBURG', name='trregionenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_report', 'region',
               existing_type=postgresql.ENUM('KRASNODAR', 'STAVROPOL', 'CRIMEA', 'ALTAI', 'PETESBURG', name='trregionenum'),
               nullable=True)
    # ### end Alembic commands ###
