"""delete relationship

Revision ID: b0df8d13567a
Revises: c4abb32345bc
Create Date: 2023-06-20 15:11:10.141730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0df8d13567a'
down_revision = 'c4abb32345bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transation_in', sa.Column('transaction_out_hash', sa.String(), nullable=True))
    op.drop_constraint('transation_in_transaction_out_id_fkey', 'transation_in', type_='foreignkey')
    op.drop_column('transation_in', 'transaction_out_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transation_in', sa.Column('transaction_out_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transation_in_transaction_out_id_fkey', 'transation_in', 'transaction_out', ['transaction_out_id'], ['id'])
    op.drop_column('transation_in', 'transaction_out_hash')
    # ### end Alembic commands ###
