"""delete relationship

Revision ID: b80a6e9d6364
Revises: 5f8beae088a2
Create Date: 2023-06-20 14:45:23.188642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80a6e9d6364'
down_revision = '5f8beae088a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
