"""add relationship

Revision ID: b901e55ca640
Revises: b80a6e9d6364
Create Date: 2023-06-20 14:52:12.424592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b901e55ca640'
down_revision = 'b80a6e9d6364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transation_in', sa.Column('transaction_out_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transation_in', 'transaction_out', ['transaction_out_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transation_in', type_='foreignkey')
    op.drop_column('transation_in', 'transaction_out_id')
    # ### end Alembic commands ###
