"""remove tourist_hash field

Revision ID: e60b7d81e825
Revises: 6abd40b6f903
Create Date: 2023-05-04 02:43:29.400369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60b7d81e825'
down_revision = '6abd40b6f903'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'user_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('transation_in', 'tourist_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transation_in', sa.Column('tourist_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('transactions', 'user_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
